name: Check Pull Request Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          check-latest: true

      - name: Install dependencies
        run: |
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi

      - name: Check
        run: |
          npm ci
          npm run lint-diff
        env:
          CI: true
          BASE: ${{ github.base_ref }}
          HEAD: ${{ github.head_ref }}
